vault_version: "1.21.2"

vault_user: vault
vault_group: vault

vault_data_dir: /opt/vault/data
vault_config_dir: /etc/vault.d
vault_install_dir: /usr/local/bin
vault_binary_path: "{{ vault_install_dir }}/vault"


vault_consul_path: "vault/"


vault_tls_dir: "{{ vault_config_dir }}/tls"


# Network identity (derived)
vault_private_ip: "{{ ansible_default_ipv4.address }}"

vault_api_addr: >
  {{ vault_api_scheme | default('http') }}://{{ vault_private_ip }}:{{ vault_api_port }}

vault_cluster_scheme: "{{ vault_api_scheme | default('http') }}"
vault_cluster_addr: >
  {{ vault_cluster_scheme }}://{{ vault_private_ip }}:{{ vault_cluster_port }}
